"""initial schema

Revision ID: 3692b307981a
Revises: 
Create Date: 2026-07-18 20:17:25.137548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.infrastructure.crypto


# revision identifiers, used by Alembic.
revision: str = '3692b307981a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sender_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_address', sa.String(), nullable=False),
    sa.Column('content_pattern_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.Enum('UPI_DEBIT', 'UPI_CREDIT', 'CREDIT_CARD_DEBIT', 'CREDIT_CARD_CREDIT', name='transactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_name')
    )
    op.create_table('gmail_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('tokens', app.infrastructure.crypto.EncryptedText(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_connection_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNPROCESSED', 'MATCHED', 'NEEDS_REVIEW', 'IGNORED', name='emailmessagestatus'), nullable=False),
    sa.Column('content', app.infrastructure.crypto.EncryptedText(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gmail_connection_id'], ['gmail_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_connection_id', sa.Integer(), nullable=False),
    sa.Column('last_history_id', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gmail_connection_id'], ['gmail_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_connection_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('txn_time', sa.Time(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('instrument_last4', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('UPI', 'CREDIT_CARD', name='paymentmethod'), nullable=False),
    sa.Column('txn_type', sa.Enum('DEBIT', 'CREDIT', name='debitorcredit'), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('review_status', sa.Enum('AUTO_ACCEPTED', 'NEEDS_REVIEW', 'USER_CONFIRMED', name='reviewstatus'), nullable=False),
    sa.Column('email_message_id', sa.Integer(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['email_message_id'], ['email_messages.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_message_id')
    )
    op.create_table('correction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correction_log')
    op.drop_table('transactions')
    op.drop_table('sync_state')
    op.drop_table('email_messages')
    op.drop_table('gmail_connections')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('sender_rules')
    op.drop_table('payees')
    # ### end Alembic commands ###
