"""add sync health columns to sync_state (B5)

Revision ID: 96b145d41d66
Revises: 3692b307981a
Create Date: 2026-07-18 23:32:13.567057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b145d41d66'
down_revision: Union[str, None] = '3692b307981a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_state', sa.Column('last_sync_started_at', sa.DateTime(), nullable=True))
    op.add_column('sync_state', sa.Column('last_scanned', sa.Integer(), nullable=True))
    op.add_column('sync_state', sa.Column('last_matched', sa.Integer(), nullable=True))
    op.add_column('sync_state', sa.Column('last_skipped', sa.Integer(), nullable=True))
    op.add_column('sync_state', sa.Column('last_failed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_state', 'last_failed')
    op.drop_column('sync_state', 'last_skipped')
    op.drop_column('sync_state', 'last_matched')
    op.drop_column('sync_state', 'last_scanned')
    op.drop_column('sync_state', 'last_sync_started_at')
    # ### end Alembic commands ###
