"""add classified_pattern_id to email_messages (C7)

Revision ID: e5aa5f25c7b3
Revises: 96b145d41d66
Create Date: 2026-07-18 23:59:55.540390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5aa5f25c7b3'
down_revision: Union[str, None] = '96b145d41d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('classified_pattern_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'classified_pattern_id')
    # ### end Alembic commands ###
